name: "Evolve Schema"
description: "Generate (Evolved) Schema For Kafka Schema Registry from .NET type"

inputs:
  assembly-path:
    required: false
    default: ""
  type-name:
    required: false
    default: ""
  format:
    required: false
    default: ""
  current-latest-schema-path:
    required: false
    default: ""
  output-path:
    required: false
    default: ""
  params-file:
    required: false
    default: ""

runs:
  using: "composite"

  env:
    tmp-action-src-folder: "/tmp/tools/evolve-schema-src"

  steps:
    - name: Checkout Action Repo for sources (because they are not available when run action is called from another repo)
      uses: actions/checkout@v4
      with:
        repository: Clark1992/kafka-schema-generator
        path: ${{ env.tmp-action-src-folder }}
        
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Show All folder structure
      run: |
        echo "All tree ."
        tree .
      shell: bash

    - name: Run generator with separate inputs
      if: ${{ inputs.params-file == '' }}
      run: |
        dotnet run --configuration Release \
          --project "${{ env.tmp-action-src-folder }}/KafkaSchemaGenerator/KafkaSchemaEvolutioner/KafkaSchemaEvolutioner.csproj" \
          "${{ inputs.assembly-path }}" \
          "${{ inputs.type-name }}" \
          "${{ inputs.format }}" \
          "${{ inputs.current-latest-schema-path }}" \
          "${{ inputs.output-path }}"
      shell: bash

    - name: Run generator with params file
      if: ${{ inputs.params-file != '' }}
      run: |
        dotnet run --configuration Release \
          --project "${{ env.tmp-action-src-folder }}/KafkaSchemaGenerator/KafkaSchemaEvolutioner/KafkaSchemaEvolutioner.csproj" \
          "${{ inputs.params-file }}"
      shell: bash