name: "Evolve Schema"
description: "Generate (Evolved) Schema For Kafka Schema Registry from .NET type"

inputs:
  assembly-path:
    required: true
  type-name:
    required: true
  format:
    required: false
    default: json
  current-latest-schema-path:
    required: true
  output-path:
    required: false
    default: "output"

runs:
  using: "composite"
  steps:
    - name: Checkout Action Repo for sources (because they are not available when run action is called from another repo)
      uses: actions/checkout@v4
      with:
        repository: Clark1992/kafka-schema-generator
        path: tools/evolve-schema-src
        
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Show All folder structure
      run: |
        echo "All tree ."
        tree .
      shell: bash

    - run: dotnet run --configuration Release --project "tools/evolve-schema-src/KafkaSchemaGenerator/KafkaSchemaEvolutioner/KafkaSchemaEvolutioner.csproj" \
          "${{ inputs.assembly-path }}" \
          "${{ inputs.type-name }}" \
          "${{ inputs.format }}" \
          "${{ inputs.current-latest-schema-path }}" \
          "${{ inputs.output-path }}"
      shell: bash
