name: "Evolve Schema"
description: "Generate (Evolved) Schema For Kafka Schema Registry from .NET type"

inputs:
  assembly-path:
    required: true
  type-name:
    required: true
  format:
    required: false
    default: json
  current-latest-schema-path:
    required: true
  output-path:
    required: false
    default: "output"

runs:
  using: "composite"
  steps:
    - name: Checkout this repo (action repo)
      uses: actions/checkout@v3
      with:
        repository: ${{ github.action_repository }}
        ref: ${{ github.action_ref }}
        token: ${{ github.token }}
        
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Show action folder structure
      run: |
        echo "Action path: ${{ github.action_path }}"
        tree "${{ github.action_path }}"
      shell: bash

    - run: dotnet run --project "${{ github.action_path }}/KafkaSchemaGenerator/KafkaSchemaEvolutioner/KafkaSchemaEvolutioner.csproj" \
          "${{ inputs.assembly-path }}" \
          "${{ inputs.type-name }}" \
          "${{ inputs.format }}" \
          "${{ inputs.current-latest-schema-path }}" \
          "${{ inputs.output-path }}"
      shell: bash
