name: CI & Update stable

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore
        working-directory: KafkaSchemaGenerator

      - run: dotnet build --configuration Release
        working-directory: KafkaSchemaGenerator

      - run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"
        working-directory: KafkaSchemaGenerator

      - name: Upload test results
        uses: actions/upload-artifact@v4
        working-directory: KafkaSchemaGenerator
        if: always()
        with:
          name: test-results
          path: '**/TestResults/**/*.trx'

      - name: Publish test results to GitHub
        uses: dorny/test-reporter@v1
        working-directory: KafkaSchemaGenerator
        if: always()
        with:
          name: Unit Tests
          path: '**/TestResults/**/*.trx'
          reporter: vstest
          fail-on-error: false

  update-stable:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update stable branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git checkout main
          git push origin HEAD:stable-v1 --force
